name: Auto Update README

on:
  schedule:
    - cron: '0 * * * *'   # every hour
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (none required) & run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}    # optional
        run: |
          node ./scripts/update-readme.js

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md || true
          if git diff --cached --quiet; then
            echo "No README changes to commit."
          else
            git commit -m "chore(readme): auto-update README (now-working / stats)"
            git push
          fi
